insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("gram", "컴퓨터", 100,"LG",50)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("울트라", "컴퓨터", 110,"삼성",30)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("아이패드", "스마트기기", 40,"APPLE",20)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("갤럭시s105G", "핸드폰", 140,"삼성",10)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("갤럭시 S9", "핸드폰", 110,"삼성",25)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("갤럭시탭", "스마트기기",80,"삼성",100)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("운동화1", "신발", 8,"아디다스",30)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("운동화2", "신발", 11,"나이키",20)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("에어팟", "이어폰", 16,"APPLE",10)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("버즈", "이어폰", 9,"삼성",15)
insert into product_table(name, category, price, manufacturer, unit_in_stock) values ("마우스2", "마우스", 3,"LOGITECH",24)